OBJS += frontends/systemverilog/UhdmAst.o
OBJS += frontends/systemverilog/uhdmastfrontend.o
OBJS += frontends/systemverilog/uhdmcommonfrontend.o
OBJS += frontends/systemverilog/uhdmsurelogastfrontend.o
OBJS += frontends/systemverilog/uhdmastreport.o
OBJS += frontends/systemverilog/third_party/yosys/const2ast.o
